import unittest
from unittest.mock import patch, mock_open, MagicMock
import tempfile
import os
import shutil
from tracker.log_reader import (
    get_all_log_files, 
    parse_log_file, 
    get_all_applications, 
    get_tracker_summary, 
    delete_application_log
)

class TestLogReader(unittest.TestCase):
    def setUp(self):
        self.test_dir = tempfile.mkdtemp()
        
    def tearDown(self):
        shutil.rmtree(self.test_dir)

    def test_get_all_log_files_returns_sorted_list(self):
        # Create fake log files with different modification times
        f1 = os.path.join(self.test_dir, "log_1.txt")
        f2 = os.path.join(self.test_dir, "log_2.txt")
        f3 = os.path.join(self.test_dir, "log_3.txt")
        
        with open(f1, "w") as f: f.write("test1")
        os.utime(f1, (1000, 1000)) # Oldest
        
        with open(f2, "w") as f: f.write("test2")
        os.utime(f2, (3000, 3000)) # Newest
        
        with open(f3, "w") as f: f.write("test3")
        os.utime(f3, (2000, 2000)) # Middle
        
        real_join = os.path.join
        real_getmtime = os.path.getmtime
        with patch('tracker.log_reader.os.path.exists', return_value=True), \
             patch('tracker.log_reader.os.path.isdir', return_value=True), \
             patch('tracker.log_reader.os.listdir', return_value=["log_1.txt", "log_2.txt", "log_3.txt"]), \
             patch('tracker.log_reader.os.path.join', side_effect=lambda a, b: real_join(self.test_dir, b)), \
             patch('tracker.log_reader.os.path.getmtime', side_effect=lambda x: real_getmtime(x)):
            
            files = get_all_log_files()
            self.assertEqual(len(files), 3)
            # Should be f2, f3, f1 based on mtime reverse=True
            self.assertEqual(os.path.basename(files[0]), "log_2.txt")
            self.assertEqual(os.path.basename(files[1]), "log_3.txt")
            self.assertEqual(os.path.basename(files[2]), "log_1.txt")

    def test_parse_log_file_extracts_all_fields(self):
        log_content = """JobCrew — Generated Application Materials
Candidate: John Doe
Job: Software Engineer at VA
Generated: 2026-04-18 10:00:00

==================================================
JOB ANALYSIS
==================================================
Analysis content here.

==================================================
RESUME AND COVER LETTER
==================================================
Resume content here.

==================================================
LINKEDIN MESSAGE
==================================================
Message content here.

Generated by JobCrew — AI-Powered Job Application Assistant
"""
        temp_log = os.path.join(self.test_dir, "log_test.txt")
        with open(temp_log, "w", encoding="utf-8") as f:
            f.write(log_content)
            
        result = parse_log_file(temp_log)
        
        self.assertEqual(result['job_title'], "Software Engineer")
        self.assertEqual(result['department'], "VA")
        self.assertEqual(result['candidate_name'], "John Doe")
        self.assertIn("job_analysis", result)
        self.assertIn("resume_and_cover_letter", result)
        self.assertIn("linkedin_message", result)

    @patch('tracker.log_reader.get_all_log_files')
    @patch('tracker.log_reader.parse_log_file')
    def test_get_all_applications_skips_malformed_files(self, mock_parse, mock_get_files):
        mock_get_files.return_value = ["log1.txt", "log2.txt", "empty.txt"]
        
        def side_effect(path):
            if "empty" in path:
                raise ValueError("Empty file")
            return {"job_title": "Job", "generated_at": "2026"}
            
        mock_parse.side_effect = side_effect
        
        apps = get_all_applications()
        self.assertEqual(len(apps), 2)

    @patch('tracker.log_reader.get_all_applications')
    def test_get_tracker_summary_returns_correct_counts(self, mock_get_apps):
        mock_get_apps.return_value = [
            {"department": "VA", "file_size_kb": 5.0, "generated_at": "2026-04-18 10:00:00"},
            {"department": "DOL", "file_size_kb": 3.0, "generated_at": "2026-04-18 09:00:00"},
            {"department": "VA", "file_size_kb": 2.0, "generated_at": "2026-04-18 08:00:00"}
        ]
        
        summary = get_tracker_summary()
        self.assertEqual(summary['total_applications'], 3)
        self.assertEqual(len(summary['unique_departments']), 2)
        self.assertIn("VA", summary['unique_departments'])
        self.assertIn("DOL", summary['unique_departments'])

    def test_delete_application_log_removes_file(self):
        # Create logs directory in temp dir
        logs_path = os.path.join(self.test_dir, "logs")
        os.makedirs(logs_path)
        temp_file = os.path.join(logs_path, "log_test123.txt")
        with open(temp_file, "w") as f: f.write("test")
        
        real_join = os.path.join
        real_exists = os.path.exists
        real_remove = os.remove
        with patch('tracker.log_reader.os.path.exists', side_effect=lambda x: real_exists(x)), \
             patch('tracker.log_reader.os.path.join', side_effect=lambda a, b: real_join(logs_path, b)), \
             patch('tracker.log_reader.os.remove', side_effect=lambda x: real_remove(x)):
            
            result = delete_application_log("log_test123")
            self.assertTrue(result)
            self.assertFalse(os.path.exists(temp_file))

if __name__ == '__main__':
    unittest.main()
