import os
import re
import time

_applications_cache = None
_cache_timestamp = None

def get_all_log_files():
    logs_dir = 'logs'
    if not os.path.exists(logs_dir) or not os.path.isdir(logs_dir):
        return []
    
    files = [os.path.join(logs_dir, f) for f in os.listdir(logs_dir) if f.endswith('.txt')]
    files.sort(key=lambda x: os.path.getmtime(x), reverse=True)
    return files

def parse_log_file(file_path):
    filename = os.path.basename(file_path)
    log_id = os.path.splitext(filename)[0]
    
    job_id = log_id.replace("log_", "")
    
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()
        
    # Extract header lines
    lines = content.splitlines()
    header_lines = []
    for line in lines:
        if line.startswith("==="):
            break
        header_lines.append(line)
        
    candidate_name = ""
    job_title = ""
    department = ""
    generated_at = ""
    
    for line in header_lines:
        line = line.strip()
        if line.startswith("Candidate:"):
            candidate_name = line.split("Candidate:", 1)[1].strip()
        elif line.startswith("Job:"):
            job_str = line.split("Job:", 1)[1].strip()
            if " at " in job_str:
                job_title, department = job_str.split(" at ", 1)
                job_title = job_title.strip()
                department = department.strip()
            else:
                job_title = job_str
        elif line.startswith("Generated:"):
            generated_at = line.split("Generated:", 1)[1].strip()
        # Backwards compatibility for old logs
        elif line.startswith("Job Title:"):
            job_title = line.split("Job Title:", 1)[1].strip()
        elif line.startswith("Department:"):
            department = line.split("Department:", 1)[1].strip()
        elif line.startswith("Timestamp:"):
            generated_at = line.split("Timestamp:", 1)[1].strip()

    job_analysis = ""
    resume_and_cover_letter = ""
    linkedin_message = ""
    
    parts = re.split(r'={20,}', content)
    for i in range(len(parts) - 1):
        header_text = parts[i].strip()
        body_text = parts[i+1].strip()
        
        if header_text == "JOB ANALYSIS":
            job_analysis = body_text
        elif header_text in ["RESUME AND COVER LETTER", "RESUME & COVER LETTER"]:
            resume_and_cover_letter = body_text
        elif header_text == "LINKEDIN MESSAGE":
            linkedin_message = body_text
            if linkedin_message.endswith("Generated by JobCrew — AI-Powered Job Application Assistant"):
                linkedin_message = linkedin_message.replace("Generated by JobCrew — AI-Powered Job Application Assistant", "").strip()

    file_size_kb = round(os.path.getsize(file_path) / 1024, 2)
    
    return {
        "log_id": log_id,
        "job_id": job_id,
        "job_title": job_title,
        "department": department,
        "candidate_name": candidate_name,
        "generated_at": generated_at,
        "job_analysis": job_analysis,
        "resume_and_cover_letter": resume_and_cover_letter,
        "linkedin_message": linkedin_message,
        "file_path": file_path,
        "file_size_kb": file_size_kb
    }

def invalidate_applications_cache():
    global _applications_cache, _cache_timestamp
    _applications_cache = None
    _cache_timestamp = None
    print("[Cache] Applications cache invalidated")

def get_all_applications():
    global _applications_cache, _cache_timestamp
    if _applications_cache is not None and _cache_timestamp is not None:
        if (time.time() - _cache_timestamp) < 60:
            return _applications_cache

    files = get_all_log_files()
    apps = []
    for f in files:
        try:
            apps.append(parse_log_file(f))
        except Exception as e:
            print(f"Warning: Failed to parse {f}: {e}")
            
    apps.sort(key=lambda x: x.get("generated_at", ""), reverse=True)
    _applications_cache = apps
    _cache_timestamp = time.time()
    return apps

def get_application_by_id(log_id):
    file_path = os.path.join('logs', f"{log_id}.txt")
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Log file not found for ID: {log_id}")
    
    return parse_log_file(file_path)

def delete_application_log(log_id):
    file_path = os.path.join('logs', f"{log_id}.txt")
    if not os.path.exists(file_path):
        raise FileNotFoundError(f"Log file not found for ID: {log_id}")
        
    os.remove(file_path)
    invalidate_applications_cache()
    return True

def get_tracker_summary():
    apps = get_all_applications()
    total_apps = len(apps)
    departments = list(set([a["department"] for a in apps if a["department"]]))
    most_recent = apps[0]["generated_at"] if apps else None
    total_size = round(sum([a["file_size_kb"] for a in apps]), 2)
    
    return {
        "total_applications": total_apps,
        "unique_departments": departments,
        "most_recent": most_recent,
        "total_size_kb": total_size
    }

if __name__ == "__main__":
    summary = get_tracker_summary()
    print("Tracker Summary:")
    print(summary)
    
    print("\nAll Applications:")
    for app in get_all_applications():
        print(f"- {app['job_title']} ({app['generated_at']})")
