import datetime
import sys
import os

# Bulletproof path injection to resolve 'tests' module collision with site-packages
tests_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'tests'))
if tests_dir not in sys.path:
    sys.path.insert(0, tests_dir)

from prompt_quality_test import score_job_analysis_output, score_resume_output, score_messaging_output

def format_output_for_display(raw_output, output_type):
    raw_output = raw_output.strip() if raw_output else ""
    
    if output_type == "analysis":
        if "## POSITION OVERVIEW" in raw_output:
            return raw_output
        return f"## JOB ANALYSIS\n\n{raw_output}"
        
    elif output_type == "resume":
        if "## TAILORED RESUME SUMMARY" in raw_output:
            return raw_output
        return f"## GENERATED MATERIALS\n\n{raw_output}"
        
    elif output_type == "messaging":
        if "## LINKEDIN MESSAGE" in raw_output:
            return raw_output
        return f"## OUTREACH MATERIALS\n\n{raw_output}"
        
    return raw_output

def format_output_for_download(result, candidate_name):
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    job_title = result.get('job_title', 'Unknown Title')
    department = result.get('department', 'Unknown Department')
    
    header = f"JobCrew — Generated Application Materials\nCandidate: {candidate_name}\nJob: {job_title} at {department}\nGenerated: {timestamp}\n\n"
    
    analysis = result.get('job_analysis', '')
    resume = result.get('resume_and_cover_letter', '')
    messaging = result.get('linkedin_message', '')
    
    formatted = (
        f"{header}"
        f"==================================================\n"
        f"JOB ANALYSIS\n"
        f"==================================================\n\n"
        f"{analysis}\n\n"
        f"==================================================\n"
        f"RESUME AND COVER LETTER\n"
        f"==================================================\n\n"
        f"{resume}\n\n"
        f"==================================================\n"
        f"LINKEDIN MESSAGE\n"
        f"==================================================\n\n"
        f"{messaging}\n\n"
        f"Generated by JobCrew — AI-Powered Job Application Assistant\n"
    )
    return formatted

def calculate_quality_indicators(result):
    ja_raw = result.get('job_analysis', '')
    res_raw = result.get('resume_and_cover_letter', '')
    msg_raw = result.get('linkedin_message', '')
    
    ja_score = score_job_analysis_output(ja_raw)
    res_score = score_resume_output(res_raw)
    msg_score = score_messaging_output(msg_raw)
    
    def get_label(score, max_score, passed):
        if passed: return "Good"
        if score > (max_score / 2): return "Partial"
        return "Poor"
        
    return {
        "analysis_quality": {
            "score": ja_score["score"],
            "max_score": ja_score["max_score"],
            "passed": ja_score["passed"],
            "label": get_label(ja_score["score"], ja_score["max_score"], ja_score["passed"])
        },
        "resume_quality": {
            "score": res_score["score"],
            "max_score": res_score["max_score"],
            "passed": res_score["passed"],
            "label": get_label(res_score["score"], res_score["max_score"], res_score["passed"])
        },
        "messaging_quality": {
            "score": msg_score["score"],
            "max_score": msg_score["max_score"],
            "passed": msg_score["passed"],
            "label": get_label(msg_score["score"], msg_score["max_score"], msg_score["passed"])
        }
    }
